SELECT SESSIONPROPERTY('SessionID') AS CurrentSessionID;
SELECT SESSIONPROPERTY('LoginName') AS CurrentLoginName;
SELECT SESSIONPROPERTY('SystemTime') AS CurrentSystemTime;
SELECT SESSIONPROPERTY('AuthenticationMode') AS CurrentAuthenticationMode;
SELECT SESSIONPROPERTY('ConnectionType') AS CurrentConnectionType;
SELECT SESSIONPROPERTY('ClientName') AS CurrentClientName;
SELECT SESSIONPROPERTY('LockTimeout') AS CurrentLockTimeout;